### ISSUE TITLE
Project Specification Generation

### ISSUE THREAD

**Issue by FredDoe** [sdt-grp-two-uestc/.github#1]
## Tasks

- [ ] Generate the requirement and specification for the project
- [ ] Merge the initial document @FredDoe created with the new ones @RubabaFred generated.
- [ ] Remove any redundancy without losing any relevant information.

**Comment by RubabaFred** [comment]
okay, Working on it.
